import React from 'react'

function BgImage() {
  return(
    <>
    
    <img src="src/assets/background.webp" alt="" srcset="" className='w-full h-full m-0 p-0 ' />
  
      <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae repellendus, sunt ad nemo quisquam at vero impedit tempora velit inventore laboriosam saepe nam, labore qui harum quaerat. Magni asperiores cupiditate reprehenderit sunt adipisci minus sit, aliquid perspiciatis sed quasi, magnam cumque facilis? Iusto odio omnis numquam doloremque ducimus tenetur accusamus saepe neque repellat dolor possimus provident eligendi architecto officiis aliquam ea blanditiis, distinctio autem nemo dolorum amet iure. Officia ad unde quis officiis quia nisi eum nemo, ipsam qui sunt cumque, esse voluptate praesentium. Ratione laboriosam animi magni! Neque mollitia id, nulla harum exercitationem perspiciatis odio necessitatibus repudiandae hic, quidem enim tempora voluptates odit eligendi velit, asperiores et totam voluptas omnis reprehenderit quae. Fuga harum deleniti ipsa facilis recusandae delectus sunt enim nostrum magni ratione inventore suscipit, reprehenderit eveniet tempora accusantium iste corporis at asperiores praesentium amet incidunt doloribus expedita aperiam. Quo possimus animi laudantium in aliquam perspiciatis exercitationem sit nobis fugit saepe? Aliquid dolore deleniti eius, explicabo autem dolor maiores. Repellat ea pariatur nesciunt rem ab delectus, aut placeat magni necessitatibus perspiciatis. Deserunt aperiam tempora, vero, aut dignissimos, quidem dolore debitis quasi natus vitae excepturi! Facilis modi autem minus dolores est nostrum consequatur, nam perferendis aut pariatur minima iste!
      </div>
      <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae repellendus, sunt ad nemo quisquam at vero impedit tempora velit inventore laboriosam saepe nam, labore qui harum quaerat. Magni asperiores cupiditate reprehenderit sunt adipisci minus sit, aliquid perspiciatis sed quasi, magnam cumque facilis? Iusto odio omnis numquam doloremque ducimus tenetur accusamus saepe neque repellat dolor possimus provident eligendi architecto officiis aliquam ea blanditiis, distinctio autem nemo dolorum amet iure. Officia ad unde quis officiis quia nisi eum nemo, ipsam qui sunt cumque, esse voluptate praesentium. Ratione laboriosam animi magni! Neque mollitia id, nulla harum exercitationem perspiciatis odio necessitatibus repudiandae hic, quidem enim tempora voluptates odit eligendi velit, asperiores et totam voluptas omnis reprehenderit quae. Fuga harum deleniti ipsa facilis recusandae delectus sunt enim nostrum magni ratione inventore suscipit, reprehenderit eveniet tempora accusantium iste corporis at asperiores praesentium amet incidunt doloribus expedita aperiam. Quo possimus animi laudantium in aliquam perspiciatis exercitationem sit nobis fugit saepe? Aliquid dolore deleniti eius, explicabo autem dolor maiores. Repellat ea pariatur nesciunt rem ab delectus, aut placeat magni necessitatibus perspiciatis. Deserunt aperiam tempora, vero, aut dignissimos, quidem dolore debitis quasi natus vitae excepturi! Facilis modi autem minus dolores est nostrum consequatur, nam perferendis aut pariatur minima iste!
      </div>
      <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae repellendus, sunt ad nemo quisquam at vero impedit tempora velit inventore laboriosam saepe nam, labore qui harum quaerat. Magni asperiores cupiditate reprehenderit sunt adipisci minus sit, aliquid perspiciatis sed quasi, magnam cumque facilis? Iusto odio omnis numquam doloremque ducimus tenetur accusamus saepe neque repellat dolor possimus provident eligendi architecto officiis aliquam ea blanditiis, distinctio autem nemo dolorum amet iure. Officia ad unde quis officiis quia nisi eum nemo, ipsam qui sunt cumque, esse voluptate praesentium. Ratione laboriosam animi magni! Neque mollitia id, nulla harum exercitationem perspiciatis odio necessitatibus repudiandae hic, quidem enim tempora voluptates odit eligendi velit, asperiores et totam voluptas omnis reprehenderit quae. Fuga harum deleniti ipsa facilis recusandae delectus sunt enim nostrum magni ratione inventore suscipit, reprehenderit eveniet tempora accusantium iste corporis at asperiores praesentium amet incidunt doloribus expedita aperiam. Quo possimus animi laudantium in aliquam perspiciatis exercitationem sit nobis fugit saepe? Aliquid dolore deleniti eius, explicabo autem dolor maiores. Repellat ea pariatur nesciunt rem ab delectus, aut placeat magni necessitatibus perspiciatis. Deserunt aperiam tempora, vero, aut dignissimos, quidem dolore debitis quasi natus vitae excepturi! Facilis modi autem minus dolores est nostrum consequatur, nam perferendis aut pariatur minima iste!
      </div>
    </>
  )
}

export default BgImage

